### PR TITLE
Corrected how tasks were being passed through to the executeCommand call for subtasks

### LINKED ISSUE #65: Subtasks not working
It seems that task button with subtasks is not working properly in 1.1.2 version of the extension.
It brings up the Quick Pick menu, but after selecting any item, it jumps to default task selection menu instead of executing what was selected.

Looks like an issue with how selected task is executed, changing this
```
vscode.commands.executeCommand(`${COMMANDS.RUN_TASK}`, [
  subTask.task,
]);
```
to this
```
vscode.commands.executeCommand(`${COMMANDS.RUN_TASK}`, 
  subTask.task,
);

```
fixed the issue for me.

### PR DESCRIPTION
**Pull request by spencerwmiles**
Fixes #65

### CODE REVIEW

**Comment by spencerwmiles** [comment]
52U0

**Comment by spencerwmiles** [comment]
https://github.com/spencerwmiles/vscode-task-buttons/assets/7152222/f51f46f8-d900-4607-8946-38294f0bf713

**Comment by spencerwmiles** [comment]
@gameguy682 @FaBjE if one of you guys don't mind, lets try and get this out today.

**Comment by gameguy682** [comment]
Code looks fine (on mobile), but I want to test this to make sure things are working.

**Review by gameguy682 — APPROVED** [review]
Took a look on a break at work. LGTM!

**Pull request merged**
